/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.raftex
{

  [Serializable]
  public partial class AskForVoteRequest : TBase
  {
    private int space;
    private int part;
    private string candidate_addr;
    private int candidate_port;
    private long term;
    private long last_log_id;
    private long last_log_term;

    public int Space
    {
      get
      {
        return space;
      }
      set
      {
        __isset.space = true;
        this.space = value;
      }
    }

    public int Part
    {
      get
      {
        return part;
      }
      set
      {
        __isset.part = true;
        this.part = value;
      }
    }

    public string Candidate_addr
    {
      get
      {
        return candidate_addr;
      }
      set
      {
        __isset.candidate_addr = true;
        this.candidate_addr = value;
      }
    }

    public int Candidate_port
    {
      get
      {
        return candidate_port;
      }
      set
      {
        __isset.candidate_port = true;
        this.candidate_port = value;
      }
    }

    public long Term
    {
      get
      {
        return term;
      }
      set
      {
        __isset.term = true;
        this.term = value;
      }
    }

    public long Last_log_id
    {
      get
      {
        return last_log_id;
      }
      set
      {
        __isset.last_log_id = true;
        this.last_log_id = value;
      }
    }

    public long Last_log_term
    {
      get
      {
        return last_log_term;
      }
      set
      {
        __isset.last_log_term = true;
        this.last_log_term = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool space;
      public bool part;
      public bool candidate_addr;
      public bool candidate_port;
      public bool term;
      public bool last_log_id;
      public bool last_log_term;
    }

    public AskForVoteRequest() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              this.space = iprot.ReadI32();
              this.__isset.space = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              this.part = iprot.ReadI32();
              this.__isset.part = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              this.candidate_addr = iprot.ReadString();
              this.__isset.candidate_addr = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              this.candidate_port = iprot.ReadI32();
              this.__isset.candidate_port = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 5:
            if (field.Type == TType.I64) {
              this.term = iprot.ReadI64();
              this.__isset.term = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 6:
            if (field.Type == TType.I64) {
              this.last_log_id = iprot.ReadI64();
              this.__isset.last_log_id = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 7:
            if (field.Type == TType.I64) {
              this.last_log_term = iprot.ReadI64();
              this.__isset.last_log_term = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AskForVoteRequest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.space) {
        field.Name = "space";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.space);
        oprot.WriteFieldEnd();
      }
      if (__isset.part) {
        field.Name = "part";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.part);
        oprot.WriteFieldEnd();
      }
      if (this.candidate_addr != null && __isset.candidate_addr) {
        field.Name = "candidate_addr";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(this.candidate_addr);
        oprot.WriteFieldEnd();
      }
      if (__isset.candidate_port) {
        field.Name = "candidate_port";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.candidate_port);
        oprot.WriteFieldEnd();
      }
      if (__isset.term) {
        field.Name = "term";
        field.Type = TType.I64;
        field.ID = 5;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(this.term);
        oprot.WriteFieldEnd();
      }
      if (__isset.last_log_id) {
        field.Name = "last_log_id";
        field.Type = TType.I64;
        field.ID = 6;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(this.last_log_id);
        oprot.WriteFieldEnd();
      }
      if (__isset.last_log_term) {
        field.Name = "last_log_term";
        field.Type = TType.I64;
        field.ID = 7;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(this.last_log_term);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AskForVoteRequest(");
      sb.Append("space: ");
      sb.Append(this.space);
      sb.Append(",part: ");
      sb.Append(this.part);
      sb.Append(",candidate_addr: ");
      sb.Append(this.candidate_addr);
      sb.Append(",candidate_port: ");
      sb.Append(this.candidate_port);
      sb.Append(",term: ");
      sb.Append(this.term);
      sb.Append(",last_log_id: ");
      sb.Append(this.last_log_id);
      sb.Append(",last_log_term: ");
      sb.Append(this.last_log_term);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
