/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.raftex
{

  [Serializable]
  public partial class LogEntry : TBase
  {
    private long cluster;
    private byte[] log_str;

    public long Cluster
    {
      get
      {
        return cluster;
      }
      set
      {
        __isset.cluster = true;
        this.cluster = value;
      }
    }

    public byte[] Log_str
    {
      get
      {
        return log_str;
      }
      set
      {
        __isset.log_str = true;
        this.log_str = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool cluster;
      public bool log_str;
    }

    public LogEntry() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              this.cluster = iprot.ReadI64();
              this.__isset.cluster = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.log_str = iprot.ReadBinary();
              this.__isset.log_str = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("LogEntry");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.cluster) {
        field.Name = "cluster";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(this.cluster);
        oprot.WriteFieldEnd();
      }
      if (this.log_str != null && __isset.log_str) {
        field.Name = "log_str";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.log_str);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("LogEntry(");
      sb.Append("cluster: ");
      sb.Append(this.cluster);
      sb.Append(",log_str: ");
      sb.Append(this.log_str);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
