/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula
{

  [Serializable]
  public partial class Vertex : TBase
  {
    private byte[] vid;
    private List<Tag> tags;

    public byte[] Vid
    {
      get
      {
        return vid;
      }
      set
      {
        __isset.vid = true;
        this.vid = value;
      }
    }

    public List<Tag> Tags
    {
      get
      {
        return tags;
      }
      set
      {
        __isset.tags = true;
        this.tags = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool vid;
      public bool tags;
    }

    public Vertex() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.vid = iprot.ReadBinary();
              this.__isset.vid = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                this.tags = new List<Tag>();
                TList _list30 = iprot.ReadListBegin();
                for( int _i31 = 0; _i31 < _list30.Count; ++_i31)
                {
                  Tag _elem32 = new Tag();
                  _elem32 = new Tag();
                  _elem32.Read(iprot);
                  this.tags.Add(_elem32);
                }
                iprot.ReadListEnd();
              }
              this.__isset.tags = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Vertex");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.vid != null && __isset.vid) {
        field.Name = "vid";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.vid);
        oprot.WriteFieldEnd();
      }
      if (this.tags != null && __isset.tags) {
        field.Name = "tags";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, this.tags.Count));
          foreach (Tag _iter33 in this.tags)
          {
            _iter33.Write(oprot);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Vertex(");
      sb.Append("vid: ");
      sb.Append(this.vid);
      sb.Append(",tags: ");
      sb.Append(this.tags);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
