/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace nebula.graph
{
  public enum ErrorCode
  {
    SUCCEEDED = 0,
    E_DISCONNECTED = -1,
    E_FAIL_TO_CONNECT = -2,
    E_RPC_FAILURE = -3,
    E_BAD_USERNAME_PASSWORD = -4,
    E_SESSION_INVALID = -5,
    E_SESSION_TIMEOUT = -6,
    E_SYNTAX_ERROR = -7,
    E_EXECUTION_ERROR = -8,
    E_STATEMENT_EMTPY = -9,
    E_USER_NOT_FOUND = -10,
    E_BAD_PERMISSION = -11,
    E_SEMANTIC_ERROR = -12,
  }
}
