/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.storage
{

  [Serializable]
  public partial class GetUUIDResp : TBase
  {
    private ResponseCommon result;
    private byte[] id;

    public ResponseCommon Result
    {
      get
      {
        return result;
      }
      set
      {
        __isset.result = true;
        this.result = value;
      }
    }

    public byte[] Id
    {
      get
      {
        return id;
      }
      set
      {
        __isset.id = true;
        this.id = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool result;
      public bool id;
    }

    public GetUUIDResp() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              this.result = new ResponseCommon();
              this.result.Read(iprot);
              this.__isset.result = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.id = iprot.ReadBinary();
              this.__isset.id = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("GetUUIDResp");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.result != null && __isset.result) {
        field.Name = "result";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        this.result.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (this.id != null && __isset.id) {
        field.Name = "id";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.id);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("GetUUIDResp(");
      sb.Append("result: ");
      sb.Append(this.result== null ? "<null>" : this.result.ToString());
      sb.Append(",id: ");
      sb.Append(this.id);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
