/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.storage
{

  [Serializable]
  public partial class KVGetResponse : TBase
  {
    private ResponseCommon result;
    private Dictionary<byte[], byte[]> key_values;

    public ResponseCommon Result
    {
      get
      {
        return result;
      }
      set
      {
        __isset.result = true;
        this.result = value;
      }
    }

    public Dictionary<byte[], byte[]> Key_values
    {
      get
      {
        return key_values;
      }
      set
      {
        __isset.key_values = true;
        this.key_values = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool result;
      public bool key_values;
    }

    public KVGetResponse() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              this.result = new ResponseCommon();
              this.result.Read(iprot);
              this.__isset.result = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Map) {
              {
                this.key_values = new Dictionary<byte[], byte[]>();
                TMap _map217 = iprot.ReadMapBegin();
                for( int _i218 = 0; _i218 < _map217.Count; ++_i218)
                {
                  byte[] _key219;
                  byte[] _val220;
                  _key219 = iprot.ReadBinary();
                  _val220 = iprot.ReadBinary();
                  this.key_values[_key219] = _val220;
                }
                iprot.ReadMapEnd();
              }
              this.__isset.key_values = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("KVGetResponse");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.result != null && __isset.result) {
        field.Name = "result";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        this.result.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (this.key_values != null && __isset.key_values) {
        field.Name = "key_values";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.String, this.key_values.Count));
          foreach (byte[] _iter221 in this.key_values.Keys)
          {
            oprot.WriteBinary(_iter221);
            oprot.WriteBinary(this.key_values[_iter221]);
            oprot.WriteMapEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("KVGetResponse(");
      sb.Append("result: ");
      sb.Append(this.result== null ? "<null>" : this.result.ToString());
      sb.Append(",key_values: ");
      sb.Append(this.key_values);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
