/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.storage
{

  [Serializable]
  public partial class LookupAndTraverseRequest : TBase
  {
    private int space_id;
    private List<int> parts;
    private IndexSpec indices;
    private TraverseSpec traverse_spec;

    public int Space_id
    {
      get
      {
        return space_id;
      }
      set
      {
        __isset.space_id = true;
        this.space_id = value;
      }
    }

    public List<int> Parts
    {
      get
      {
        return parts;
      }
      set
      {
        __isset.parts = true;
        this.parts = value;
      }
    }

    public IndexSpec Indices
    {
      get
      {
        return indices;
      }
      set
      {
        __isset.indices = true;
        this.indices = value;
      }
    }

    public TraverseSpec Traverse_spec
    {
      get
      {
        return traverse_spec;
      }
      set
      {
        __isset.traverse_spec = true;
        this.traverse_spec = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool space_id;
      public bool parts;
      public bool indices;
      public bool traverse_spec;
    }

    public LookupAndTraverseRequest() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              this.space_id = iprot.ReadI32();
              this.__isset.space_id = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                this.parts = new List<int>();
                TList _list171 = iprot.ReadListBegin();
                for( int _i172 = 0; _i172 < _list171.Count; ++_i172)
                {
                  int _elem173 = 0;
                  _elem173 = iprot.ReadI32();
                  this.parts.Add(_elem173);
                }
                iprot.ReadListEnd();
              }
              this.__isset.parts = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              this.indices = new IndexSpec();
              this.indices.Read(iprot);
              this.__isset.indices = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.Struct) {
              this.traverse_spec = new TraverseSpec();
              this.traverse_spec.Read(iprot);
              this.__isset.traverse_spec = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("LookupAndTraverseRequest");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.space_id) {
        field.Name = "space_id";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.space_id);
        oprot.WriteFieldEnd();
      }
      if (this.parts != null && __isset.parts) {
        field.Name = "parts";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I32, this.parts.Count));
          foreach (int _iter174 in this.parts)
          {
            oprot.WriteI32(_iter174);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (this.indices != null && __isset.indices) {
        field.Name = "indices";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        this.indices.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (this.traverse_spec != null && __isset.traverse_spec) {
        field.Name = "traverse_spec";
        field.Type = TType.Struct;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        this.traverse_spec.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("LookupAndTraverseRequest(");
      sb.Append("space_id: ");
      sb.Append(this.space_id);
      sb.Append(",parts: ");
      sb.Append(this.parts);
      sb.Append(",indices: ");
      sb.Append(this.indices== null ? "<null>" : this.indices.ToString());
      sb.Append(",traverse_spec: ");
      sb.Append(this.traverse_spec== null ? "<null>" : this.traverse_spec.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
