/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.storage
{

  [Serializable]
  public partial class NewTag : TBase
  {
    private int tag_id;
    private List<nebula.Value> props;

    public int Tag_id
    {
      get
      {
        return tag_id;
      }
      set
      {
        __isset.tag_id = true;
        this.tag_id = value;
      }
    }

    public List<nebula.Value> Props
    {
      get
      {
        return props;
      }
      set
      {
        __isset.props = true;
        this.props = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool tag_id;
      public bool props;
    }

    public NewTag() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              this.tag_id = iprot.ReadI32();
              this.__isset.tag_id = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                this.props = new List<nebula.Value>();
                TList _list78 = iprot.ReadListBegin();
                for( int _i79 = 0; _i79 < _list78.Count; ++_i79)
                {
                  nebula.Value _elem80 = new nebula.Value();
                  _elem80 = new nebula.Value();
                  _elem80.Read(iprot);
                  this.props.Add(_elem80);
                }
                iprot.ReadListEnd();
              }
              this.__isset.props = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("NewTag");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.tag_id) {
        field.Name = "tag_id";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.tag_id);
        oprot.WriteFieldEnd();
      }
      if (this.props != null && __isset.props) {
        field.Name = "props";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, this.props.Count));
          foreach (nebula.Value _iter81 in this.props)
          {
            _iter81.Write(oprot);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("NewTag(");
      sb.Append("tag_id: ");
      sb.Append(this.tag_id);
      sb.Append(",props: ");
      sb.Append(this.props);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
