/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace nebula.storage
{
  public enum OrderDirection
  {
    ASCENDING = 1,
    DESCENDING = 2,
  }
}
