/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace nebula.storage
{
  public enum ScanType
  {
    PREFIX = 1,
    RANGE = 2,
  }
}
