/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.storage
{

  [Serializable]
  public partial class TaskPara : TBase
  {
    private int space_id;
    private List<int> parts;
    private List<byte[]> task_specfic_paras;

    public int Space_id
    {
      get
      {
        return space_id;
      }
      set
      {
        __isset.space_id = true;
        this.space_id = value;
      }
    }

    public List<int> Parts
    {
      get
      {
        return parts;
      }
      set
      {
        __isset.parts = true;
        this.parts = value;
      }
    }

    public List<byte[]> Task_specfic_paras
    {
      get
      {
        return task_specfic_paras;
      }
      set
      {
        __isset.task_specfic_paras = true;
        this.task_specfic_paras = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool space_id;
      public bool parts;
      public bool task_specfic_paras;
    }

    public TaskPara() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              this.space_id = iprot.ReadI32();
              this.__isset.space_id = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                this.parts = new List<int>();
                TList _list183 = iprot.ReadListBegin();
                for( int _i184 = 0; _i184 < _list183.Count; ++_i184)
                {
                  int _elem185 = 0;
                  _elem185 = iprot.ReadI32();
                  this.parts.Add(_elem185);
                }
                iprot.ReadListEnd();
              }
              this.__isset.parts = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.List) {
              {
                this.task_specfic_paras = new List<byte[]>();
                TList _list186 = iprot.ReadListBegin();
                for( int _i187 = 0; _i187 < _list186.Count; ++_i187)
                {
                  byte[] _elem188 = null;
                  _elem188 = iprot.ReadBinary();
                  this.task_specfic_paras.Add(_elem188);
                }
                iprot.ReadListEnd();
              }
              this.__isset.task_specfic_paras = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("TaskPara");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.space_id) {
        field.Name = "space_id";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(this.space_id);
        oprot.WriteFieldEnd();
      }
      if (this.parts != null && __isset.parts) {
        field.Name = "parts";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.I32, this.parts.Count));
          foreach (int _iter189 in this.parts)
          {
            oprot.WriteI32(_iter189);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (this.task_specfic_paras != null && __isset.task_specfic_paras) {
        field.Name = "task_specfic_paras";
        field.Type = TType.List;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, this.task_specfic_paras.Count));
          foreach (byte[] _iter190 in this.task_specfic_paras)
          {
            oprot.WriteBinary(_iter190);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("TaskPara(");
      sb.Append("space_id: ");
      sb.Append(this.space_id);
      sb.Append(",parts: ");
      sb.Append(this.parts);
      sb.Append(",task_specfic_paras: ");
      sb.Append(this.task_specfic_paras);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
