/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace nebula.meta
{
  public enum AdminCmd
  {
    COMPACT = 0,
    FLUSH = 1,
    REBUILD_TAG_INDEX = 2,
    REBUILD_EDGE_INDEX = 3,
  }
}
