/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace nebula.meta
{
  public enum AlterSchemaOp
  {
    ADD = 1,
    CHANGE = 2,
    DROP = 3,
    UNKNOWN = 4,
  }
}
