/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.meta
{

  [Serializable]
  public partial class AlterSchemaItem : TBase
  {
    private AlterSchemaOp op;
    private Schema schema;

    public AlterSchemaOp Op
    {
      get
      {
        return op;
      }
      set
      {
        __isset.op = true;
        this.op = value;
      }
    }

    public Schema Schema
    {
      get
      {
        return schema;
      }
      set
      {
        __isset.schema = true;
        this.schema = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool op;
      public bool schema;
    }

    public AlterSchemaItem() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              this.op = (AlterSchemaOp)iprot.ReadI32();
              this.__isset.op = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              this.schema = new Schema();
              this.schema.Read(iprot);
              this.__isset.schema = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AlterSchemaItem");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.op) {
        field.Name = "op";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32((int)this.op);
        oprot.WriteFieldEnd();
      }
      if (this.schema != null && __isset.schema) {
        field.Name = "schema";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        this.schema.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AlterSchemaItem(");
      sb.Append("op: ");
      sb.Append(this.op);
      sb.Append(",schema: ");
      sb.Append(this.schema== null ? "<null>" : this.schema.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
