/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.meta
{

  [Serializable]
  public partial class DropSpaceReq : TBase
  {
    private byte[] space_name;
    private bool if_exists;

    public byte[] Space_name
    {
      get
      {
        return space_name;
      }
      set
      {
        __isset.space_name = true;
        this.space_name = value;
      }
    }

    public bool If_exists
    {
      get
      {
        return if_exists;
      }
      set
      {
        __isset.if_exists = true;
        this.if_exists = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool space_name;
      public bool if_exists;
    }

    public DropSpaceReq() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.space_name = iprot.ReadBinary();
              this.__isset.space_name = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              this.if_exists = iprot.ReadBool();
              this.__isset.if_exists = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("DropSpaceReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.space_name != null && __isset.space_name) {
        field.Name = "space_name";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.space_name);
        oprot.WriteFieldEnd();
      }
      if (__isset.if_exists) {
        field.Name = "if_exists";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(this.if_exists);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("DropSpaceReq(");
      sb.Append("space_name: ");
      sb.Append(this.space_name);
      sb.Append(",if_exists: ");
      sb.Append(this.if_exists);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
