/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace nebula.meta
{
  public enum HostStatus
  {
    ONLINE = 0,
    OFFLINE = 1,
    UNKNOWN = 2,
  }
}
