/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace nebula.meta
{
  public enum JobStatus
  {
    QUEUE = 1,
    RUNNING = 2,
    FINISHED = 3,
    FAILED = 4,
    STOPPED = 5,
    INVALID = 255,
  }
}
