/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace nebula.meta
{
  public enum PropertyType
  {
    UNKNOWN = 0,
    BOOL = 1,
    INT64 = 2,
    VID = 3,
    FLOAT = 4,
    DOUBLE = 5,
    STRING = 6,
    FIXED_STRING = 7,
    INT8 = 8,
    INT16 = 9,
    INT32 = 10,
    TIMESTAMP = 21,
    DATE = 24,
    DATETIME = 25,
    TIME = 26,
  }
}
