/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.meta
{

  [Serializable]
  public partial class ScanReq : TBase
  {
    private byte[] segment;
    private byte[] start;
    private byte[] end;

    public byte[] Segment
    {
      get
      {
        return segment;
      }
      set
      {
        __isset.segment = true;
        this.segment = value;
      }
    }

    public byte[] Start
    {
      get
      {
        return start;
      }
      set
      {
        __isset.start = true;
        this.start = value;
      }
    }

    public byte[] End
    {
      get
      {
        return end;
      }
      set
      {
        __isset.end = true;
        this.end = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool segment;
      public bool start;
      public bool end;
    }

    public ScanReq() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              this.segment = iprot.ReadBinary();
              this.__isset.segment = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.String) {
              this.start = iprot.ReadBinary();
              this.__isset.start = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              this.end = iprot.ReadBinary();
              this.__isset.end = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ScanReq");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.segment != null && __isset.segment) {
        field.Name = "segment";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.segment);
        oprot.WriteFieldEnd();
      }
      if (this.start != null && __isset.start) {
        field.Name = "start";
        field.Type = TType.String;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.start);
        oprot.WriteFieldEnd();
      }
      if (this.end != null && __isset.end) {
        field.Name = "end";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(this.end);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ScanReq(");
      sb.Append("segment: ");
      sb.Append(this.segment);
      sb.Append(",start: ");
      sb.Append(this.start);
      sb.Append(",end: ");
      sb.Append(this.end);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
