/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace nebula.meta
{

  [Serializable]
  public partial class Schema : TBase
  {
    private List<ColumnDef> columns;
    private SchemaProp schema_prop;

    public List<ColumnDef> Columns
    {
      get
      {
        return columns;
      }
      set
      {
        __isset.columns = true;
        this.columns = value;
      }
    }

    public SchemaProp Schema_prop
    {
      get
      {
        return schema_prop;
      }
      set
      {
        __isset.schema_prop = true;
        this.schema_prop = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool columns;
      public bool schema_prop;
    }

    public Schema() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                this.columns = new List<ColumnDef>();
                TList _list0 = iprot.ReadListBegin();
                for( int _i1 = 0; _i1 < _list0.Count; ++_i1)
                {
                  ColumnDef _elem2 = new ColumnDef();
                  _elem2 = new ColumnDef();
                  _elem2.Read(iprot);
                  this.columns.Add(_elem2);
                }
                iprot.ReadListEnd();
              }
              this.__isset.columns = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              this.schema_prop = new SchemaProp();
              this.schema_prop.Read(iprot);
              this.__isset.schema_prop = true;
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Schema");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (this.columns != null && __isset.columns) {
        field.Name = "columns";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, this.columns.Count));
          foreach (ColumnDef _iter3 in this.columns)
          {
            _iter3.Write(oprot);
            oprot.WriteListEnd();
          }
        }
        oprot.WriteFieldEnd();
      }
      if (this.schema_prop != null && __isset.schema_prop) {
        field.Name = "schema_prop";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        this.schema_prop.Write(oprot);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Schema(");
      sb.Append("columns: ");
      sb.Append(this.columns);
      sb.Append(",schema_prop: ");
      sb.Append(this.schema_prop== null ? "<null>" : this.schema_prop.ToString());
      sb.Append(")");
      return sb.ToString();
    }

  }

}
